spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/example_db
    username: example_user
    password: "!QAZxsw2"
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate